language: scala
jdk:
  - openjdk8
scala:
  - 2.12.10
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
stages:
  - name: test
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never